# SPDX-License-Identifier: GPL-3.0-only
import pytest
from pyarn import lockfile  # type: ignore

from hermeto.core.errors import PackageRejected
from hermeto.core.package_managers.javascript.package_json import PackageJson
from hermeto.core.package_managers.javascript.yarn_classic.main import _verify_repository
from hermeto.core.package_managers.javascript.yarn_classic.project import Project, YarnLock
from hermeto.core.rooted_path import RootedPath

VALID_PACKAGE_JSON_FILE = """
{
  "name": "camelot",
  "packageManager": "yarn@3.6.1"
}
"""

PNP_PACKAGE_JSON_FILE = """
{
  "name": "camelot",
  "packageManager": "yarn@3.6.1",
  "installConfig": {
    "pnp": true
  }
}
"""

INVALID_JSON_FILE = "totally not json"

VALID_YARN_LOCK_FILE = """
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
"""

EMPTY_YARN_LOCK_FILE = """

"""

INVALID_YARN_LOCK_FILE = """
# yarn lockfile v1
package-1
  version "1.0.3"
"""


# --- PackageJson tests ---


def _prepare_package_json_file(rooted_tmp_path: RootedPath, content: str) -> PackageJson:
    path = rooted_tmp_path.join_within_root("package.json")

    with open(path, "w") as f:
        f.write(content)

    return PackageJson.from_dir(rooted_tmp_path.path)


def test_package_json_path(rooted_tmp_path: RootedPath) -> None:
    package_json = _prepare_package_json_file(rooted_tmp_path, VALID_PACKAGE_JSON_FILE)
    assert package_json.path == rooted_tmp_path.join_within_root("package.json").path


def test_parse_package_json(rooted_tmp_path: RootedPath) -> None:
    package_json = _prepare_package_json_file(rooted_tmp_path, VALID_PACKAGE_JSON_FILE)
    assert package_json["packageManager"] == "yarn@3.6.1"


def test_parse_invalid_package_json(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        _prepare_package_json_file(rooted_tmp_path, INVALID_JSON_FILE)


def test_parse_missing_package_json(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        PackageJson.from_dir(rooted_tmp_path.path)


# --- YarnLock tests ---


def _prepare_yarn_lock_file(rooted_tmp_path: RootedPath, content: str) -> YarnLock:
    path = rooted_tmp_path.join_within_root("yarn.lock")

    with open(path, "w") as f:
        f.write(content)

    return YarnLock.from_file(path)


def test_yarn_lock_path(rooted_tmp_path: RootedPath) -> None:
    yarn_lock = _prepare_yarn_lock_file(rooted_tmp_path, VALID_YARN_LOCK_FILE)
    assert yarn_lock.path.root == rooted_tmp_path.root


def test_parse_yarn_lock(rooted_tmp_path: RootedPath) -> None:
    yarn_lock = _prepare_yarn_lock_file(rooted_tmp_path, VALID_YARN_LOCK_FILE)
    assert yarn_lock.data == lockfile.Lockfile.from_str(VALID_YARN_LOCK_FILE).data


def test_parse_empty_yarn_lock(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        _prepare_yarn_lock_file(rooted_tmp_path, EMPTY_YARN_LOCK_FILE)


def test_parse_invalid_yarn_lock(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        _prepare_yarn_lock_file(rooted_tmp_path, INVALID_YARN_LOCK_FILE)


def test_parse_missing_yarn_lock(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        path = rooted_tmp_path.join_within_root("yarn.lock")
        YarnLock.from_file(path)


# --- Project tests ---


def _setup_pnp_installs(rooted_tmp_path: RootedPath, pnp_kind: str) -> None:
    if pnp_kind == "node":
        rooted_tmp_path.join_within_root("node_modules").path.mkdir()
    if pnp_kind == "pnp_cjs":
        rooted_tmp_path.join_within_root("foo.pnp.cjs").path.touch()


@pytest.mark.parametrize(
    "package_json_content, pnp_kind",
    [
        pytest.param(PNP_PACKAGE_JSON_FILE, "install_config", id="installConfig"),
        pytest.param(VALID_PACKAGE_JSON_FILE, "node", id="node"),
        pytest.param(VALID_PACKAGE_JSON_FILE, "pnp_cjs", id="pnp_cjs"),
    ],
)
def test_pnp_installs_true(
    rooted_tmp_path: RootedPath,
    package_json_content: str,
    pnp_kind: str,
) -> None:
    _prepare_package_json_file(rooted_tmp_path, package_json_content)

    project = Project.from_source_dir(rooted_tmp_path)

    _setup_pnp_installs(rooted_tmp_path, pnp_kind)
    with pytest.raises(PackageRejected):
        _verify_repository(project)


def test_pnp_installs_false(rooted_tmp_path: RootedPath) -> None:
    _prepare_package_json_file(rooted_tmp_path, VALID_PACKAGE_JSON_FILE)
    _prepare_yarn_lock_file(rooted_tmp_path, VALID_YARN_LOCK_FILE)

    project = Project.from_source_dir(rooted_tmp_path)

    _verify_repository(project)
